### ISSUE TITLE
Setting commitTitleMatch to false does not disable commit message linting

### ISSUE THREAD

**Issue by benhodgson87** [CondeNast/conventional-pull-request-action#17]
## Expected Behavior
Setting `commitTitleMatch: 'false'` should stop the linter from checking commits within a PR.

## Actual Behavior
For our use case, because we have Github set to use the PR title for the squash merges, we have no need to ensure that the first (or any) commit follows the linting spec, however with `commitTitleMatch: 'false'` set, we still receive errors for PRs with a single commit when some part of that single commit does not follow the linting rules.

```
Error: COMMIT: PRs with a single commit require the commit message to conform to the conventional commit spec
```

In the case of the above error, it was a Dependabot PR with a single commit which actually passed correctly for the title, but was failing on;
> Error: Commit message: body's lines must not be longer than 100 characters

## Steps to Reproduce the Problem

```
name: Lint PR Title

on:
  pull_request:
    branches:
      - development
    types:
      - opened
      - edited

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Lint PR Title
        uses: CondeNast/conventional-pull-request-action@v0.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitlintRulesPath: './commitlint.rules.js'
          commitTitleMatch: 'false'
```

I think the issue here, as outlined in #18 is that even with the `commitTitleMatch` set to `false`, the linter will still lint the content of the first single commit to the default commitlint ruleset, and only skips the check that ensures it matches the title. This is desirable for users who merge commit, but don't care about their PR title, but for reverse situations like the above it would be preferable to have an option to completely skip all commit message linting when their content is irrelevant.
